apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-node
  template:
    metadata:
      labels:
        app: selenium-node
        browser: chrome
    spec:
      containers:
        - name: selenium-node
          image: selenium/standalone-chrome
          env:
            - name: HUB_HOST
              value: "selenium-hub"
            - name: HUB_PORT
              value: "4444"
          ports:
            - containerPort: 4444
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-node
spec:
  ports:
    - port: 4444
      targetPort: 4444
  selector:
    app: selenium-node
    browser: chrome
  type: LoadBalancer
