apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: dcm-selenium-dev # Namespace para el entorno de desarrollo
nameSuffix: "-dev"
patches:
  - target:
      kind: Ingress
      name: docker-selenium-selenium-ingress
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        annotations:
          kubernetes.io/ingress.class: "nginx"
        name: dcm-ingress-selenium-dev
        namespace: dcm-selenium-dev
      spec:
        rules:
          - host: selenium-dev.daniela.net  # Ajusta el host para el entorno de desarrollo
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: docker-selenium-selenium-hub
                      port:
                        number: 4444
