apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmCharts/selenium-grid
helmCharts:
  - name: selenium-grid
    repo: https://www.selenium.dev/docker-selenium
    version: "0.40.0"
    releaseName: docker-selenium
    valuesInline:
      ingress.enabled: false
      autoscaling.enabled: true
      autoscaling.minReplicaCount: 1
      autoscaling.maxReplicaCount: 10
      autoscaling.scaledJobOptions.successfulJobsHistoryLimit: 1
      autoscaling.scaledJobOptions.failedJobsHistoryLimit: 1
      keda.prometheus.metricServer.enabled: true
      keda.enabled: true
