apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - selenium-grid-chart-values.yaml

helmCharts:
  - name: selenium-grid
    repo: https://www.selenium.dev/docker-selenium
    version: "0.40.0"
    releaseName: docker-selenium
    namespace: selenium-namespace
    valuesFile: values.yaml

configurations:
  - selenium-grid-chart-values.yaml