# Valores por defecto para la configuración del Selenium Grid.
# Estos valores son comunes para ambos entornos.
grid:
  selenium:
    # Personaliza las opciones de selenium-grid según tu caso.
    maxSession: 10
    port: 4444

service:
  # Este es el valor por defecto que se cambiará dependiendo del entorno.
  type: ClusterIP