apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node
spec:
  template:
    spec:
      containers:
        - name: selenium-chrome
          value: "60000" # Timeout ajustado para pre-producción
