apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node
spec:
  template:
    spec:
      containers:
      - name: selenium-node
        image: selenium/standalone-firefox
        env:
        - name: GRID_TIMEOUT
          value: "60000"

