apiVersion: v1
kind: Namespace
metadata:
  name: selenium-pre
  labels:
    env: pre
---
apiVersion: v1
kind: Namespace
metadata:
  name: selenium-pro
  labels:
    env: pro
---
apiVersion: v1
kind: Namespace
metadata:
  name: selenium-des
  labels:
    env: des
