apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/instance: jenkins
  name: pv-jenkins
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /var/nfs/k8s_pvs/jenkins
    server: 10.0.0.10
  storageClassName: nfs-csi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins
  namespace: jenkins
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
