apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs              # <--- Utiliza tu StorageClass única
  nfs:
    path: /home/dani/labs/nfs/disco01 # <--- Apunta a su carpeta exclusiva
    server: 192.168.121.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs              # <--- Kubernetes buscará un PV con esta SC
  resources:
    requests:
      storage: 10Gi