apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/instance: jenkins
  name: pv-nfs-02
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /run/media/dani/DATOS/k8s-storage/disco2
    server: 192.168.121.1
  storageClassName: nfs-lento
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-02
  namespace: jenkins
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
