apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node
spec:
  template:
    spec:
      containers:
        - name: selenium-node
          image: selenium/standalone-chrome
          env:
            - name: GRID_TIMEOUT
              value: "120000" # Timeout más largo para producción
          resources:
            requests:
              memory: "256Mi"
