apiVersion: batch/v1
kind: Job
metadata:
  namespace: artemis-dev
  generateName: cleanup-after-sync-
  labels:
    codefresh.io/cert: cleanup-job
  annotations:
      argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: dummy-run
        image: alpine
        command:
          - "sleep"
          - "40"
      restartPolicy: Never
  backoffLimit: 2   