apiVersion: batch/v1
kind: Job
metadata:
  namespace: artemis-dev
  generateName: Post-Sync-job-
  annotations:
      argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: dummy-run
        image: ubuntu
        command: ["echo", "hola dani"]
      restartPolicy: Never
  backoffLimit: 2   