apiVersion: v1
kind: PersistentVolume
metadata:
  name: artemis-dev-pv
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /storage-local/amq

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artemis-dev-pvc
  namespace: artemis-dev
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

