apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node
spec:
  template:
    spec:
      containers:
        - name: selenium-node
          env:
            - name: GRID_TIMEOUT
              value: "30000" # Timeout más corto para desarrollo
